---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: jacopen/rancher-cli
inputs:
  - name: bottle
run:
  path: bottle/ci/tasks/deploy-production.sh
  args: [
    --input-dir, bottle
  ]
