---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: python
    tag: 3.6
inputs:
  - name: bottle
outputs:
  - name: out
run:
  path: bottle/ci/tasks/integration.sh
  args: [
    --input-dir, bottle
  ]
